fields:
  form_section:
    type: section
    display: Form Settings
  forms:
    type: suggest
    mode: form
    instructions: Select the forms where reCAPTCHA will be used.
  error_message:
    type: text
    instructions: The message that will be returned if validation fails.
  hide_badge:
    display: Hide reCAPTCHA Badge
    instructions: Replace badge with reCAPTCHA Disclaimer Message
    type: toggle
  disclaimer:
    display: Disclaimer Message
    instructions: The message shown when reCaptcha badge is hidden
    type: markdown
    show_when:
      hide_badge: true
  keys_section:
    type: section
    display: reCAPTCHA API Keys
  site_key:
    type: text
    width: 33
  secret:
    type: text
    width: 33
  invisible:
    type: toggle
    width: 33
  multi_keys_section:
    type: section
    display: reCAPTCHA API Keys (Multiple)
  multi_keys:
    type: toggle
    display: Use Multiple Keys?
  site_keys:
    type: grid
    fields:
      domains:
        type: textarea
        width: 33
      site_key:
        type: text
        display: Site Key
        width: 33
      secret:
        type: text
        width: 33
      invisible:
        type: toggle
        width: 33
